name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true
      - name: Go mod tidy
        run: go mod tidy && git diff --exit-code
      - name: Go vet
        run: go vet ./...
      - name: Go test
        run: go test ./...
